// This file is automatically generated by `build.gradle.kts` in order to keep
// the version up-to-date. Any changes to this file will automatically be
// overwritten each time the `jar` task is run. To increment the version number
// for `chrysalis`, please update the version in `build.gradle.kts`.
const val VERSION = "0.1.2"